---

- name: install snmpd
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - net-snmp
    - net-snmp-libs
    - net-snmp-utils
  become: yes

- name: setup snmp service
  service:
    name: snmpd
    enabled: yes
  become: yes  

- name: snmp trap cron
  cron:
    job: "/bin/snmptrap -v 2c -c public {{ lma_server }} '' 1.3.6.1.4.1.8072.2.3.0.1 1.3.6.1.4.1.8072.2.3.2.1 i 123456"
    minute: "*/5"
    name: simple snmp trap demo
    user: root
  become: yes
